// <auto-generated />
using System;
using FinalExam.WebApi.Repository.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalExam.WebApi.Migrations
{
    [DbContext(typeof(ChinookDbContext))]
    partial class ChinookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalExam.WebApi.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("albumId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasMaxLength(160);

                    b.HasKey("AlbumId")
                        .HasName("album_id_pkey");

                    b.HasIndex("ArtistId")
                        .HasName("album_artist_idx");

                    b.ToTable("album");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("artistId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(120);

                    b.HasKey("ArtistId")
                        .HasName("artist_id_pkey");

                    b.ToTable("artist");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customerId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasMaxLength(70);

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasMaxLength(40);

                    b.Property<string>("Company")
                        .HasColumnName("company")
                        .HasMaxLength(80);

                    b.Property<string>("Country")
                        .HasColumnName("country")
                        .HasMaxLength(40);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(60);

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasMaxLength(24);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasMaxLength(40);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasMaxLength(20);

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasMaxLength(24);

                    b.Property<string>("PostalCode")
                        .HasColumnName("postal_code")
                        .HasMaxLength(10);

                    b.Property<string>("State")
                        .HasColumnName("state")
                        .HasMaxLength(40);

                    b.Property<int?>("SupportRepId");

                    b.HasKey("CustomerId")
                        .HasName("customer_id_pkey");

                    b.HasIndex("SupportRepId")
                        .HasName("Customer_SupportRepId_idx");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("employeeId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasMaxLength(70);

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnName("birthdate")
                        .HasColumnType("datetime");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasMaxLength(40);

                    b.Property<string>("Country")
                        .HasColumnName("country")
                        .HasMaxLength(40);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(60);

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasMaxLength(24);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("HireDate")
                        .HasColumnName("hire_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasMaxLength(20);

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasMaxLength(24);

                    b.Property<string>("PostalCode")
                        .HasColumnName("postalCode")
                        .HasMaxLength(10);

                    b.Property<int?>("ReportsTo");

                    b.Property<string>("State")
                        .HasColumnName("state")
                        .HasMaxLength(40);

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasMaxLength(30);

                    b.HasKey("EmployeeId")
                        .HasName("employee_id_pkey");

                    b.HasIndex("ReportsTo")
                        .HasName("Employee_ReportsTo_idx");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("genreId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(120);

                    b.HasKey("GenreId")
                        .HasName("genre_id_pkey");

                    b.ToTable("genre");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("invoiceId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillingAddress")
                        .HasColumnName("billing_address")
                        .HasMaxLength(70);

                    b.Property<string>("BillingCity")
                        .HasColumnName("billing_city")
                        .HasMaxLength(40);

                    b.Property<string>("BillingCountry")
                        .HasColumnName("billing_country")
                        .HasMaxLength(40);

                    b.Property<string>("BillingPostalCode")
                        .HasColumnName("billing_postal_code")
                        .HasMaxLength(10);

                    b.Property<string>("BillingState")
                        .HasColumnName("billing_state")
                        .HasMaxLength(40);

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnName("invoice_date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Total")
                        .HasColumnName("total")
                        .HasColumnType("numeric(10, 2)");

                    b.HasKey("InvoiceId")
                        .HasName("invoice_id_pkey");

                    b.HasIndex("CustomerId")
                        .HasName("invoice_customerId_idx");

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.InvoiceLine", b =>
                {
                    b.Property<int>("InvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("invoiceLineId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InvoiceId");

                    b.Property<int>("Quantity");

                    b.Property<int>("TrackId");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnName("unit_price")
                        .HasColumnType("numeric(10, 2)");

                    b.HasKey("InvoiceLineId")
                        .HasName("invoiceLine_id_pkey");

                    b.HasIndex("InvoiceId")
                        .HasName("InvoiceLine_InvoiceId_idx");

                    b.HasIndex("TrackId")
                        .HasName("InvoiceLine_TrackId_idx");

                    b.ToTable("invoiceLine");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.MediaType", b =>
                {
                    b.Property<int>("MediaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("mediaTypeId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(120);

                    b.HasKey("MediaTypeId")
                        .HasName("mediaType_id_pkey");

                    b.ToTable("mediaType");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("playlistId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(120);

                    b.HasKey("PlaylistId")
                        .HasName("playlist_id_pkey");

                    b.ToTable("playlist");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.PlaylistTrack", b =>
                {
                    b.Property<int>("PlaylistId");

                    b.Property<int>("TrackId");

                    b.HasKey("PlaylistId", "TrackId")
                        .HasName("playlistId_trackId_pkey");

                    b.HasIndex("TrackId")
                        .HasName("playlist_trackTrackId_idx");

                    b.ToTable("playlistTrack");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("trackId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlbumId");

                    b.Property<int?>("Bytes");

                    b.Property<string>("Composer")
                        .HasColumnName("composer")
                        .HasMaxLength(220);

                    b.Property<int?>("GenreId");

                    b.Property<int>("MediaTypeId");

                    b.Property<int>("Milliseconds");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(200);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnName("unit_price")
                        .HasColumnType("numeric(10, 2)");

                    b.HasKey("TrackId")
                        .HasName("track_id_pkey");

                    b.HasIndex("AlbumId")
                        .HasName("Track_AlbumId_idx");

                    b.HasIndex("GenreId")
                        .HasName("Track_GenreId_idx");

                    b.HasIndex("MediaTypeId")
                        .HasName("Track_MediaTypeId_idx");

                    b.ToTable("track");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Album", b =>
                {
                    b.HasOne("FinalExam.WebApi.Models.Artist", "Artist")
                        .WithMany("Album")
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("FK_AlbumArtistId")
                        .IsRequired();
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Customer", b =>
                {
                    b.HasOne("FinalExam.WebApi.Models.Employee", "SupportRep")
                        .WithMany("Customer")
                        .HasForeignKey("SupportRepId")
                        .HasConstraintName("Customer_SupportRepId_fkey");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Employee", b =>
                {
                    b.HasOne("FinalExam.WebApi.Models.Employee", "ReportsToNavigation")
                        .WithMany("InverseReportsToNavigation")
                        .HasForeignKey("ReportsTo")
                        .HasConstraintName("Employee_ReportsTo_fkey");
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Invoice", b =>
                {
                    b.HasOne("FinalExam.WebApi.Models.Customer", "Customer")
                        .WithMany("Invoice")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("Invoice_CustomerId_fkey")
                        .IsRequired();
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.InvoiceLine", b =>
                {
                    b.HasOne("FinalExam.WebApi.Models.Invoice", "Invoice")
                        .WithMany("InvoiceLine")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("InvoiceLine_InvoiceId_fkey")
                        .IsRequired();

                    b.HasOne("FinalExam.WebApi.Models.Track", "Track")
                        .WithMany("InvoiceLine")
                        .HasForeignKey("TrackId")
                        .HasConstraintName("InvoiceLine_TrackId_fkey")
                        .IsRequired();
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.PlaylistTrack", b =>
                {
                    b.HasOne("FinalExam.WebApi.Models.Playlist", "Playlist")
                        .WithMany("PlaylistTrack")
                        .HasForeignKey("PlaylistId")
                        .HasConstraintName("PlaylistTrack_PlaylistId_fkey")
                        .IsRequired();

                    b.HasOne("FinalExam.WebApi.Models.Track", "Track")
                        .WithMany("PlaylistTrack")
                        .HasForeignKey("TrackId")
                        .HasConstraintName("PlaylistTrack_TrackId_fkey")
                        .IsRequired();
                });

            modelBuilder.Entity("FinalExam.WebApi.Models.Track", b =>
                {
                    b.HasOne("FinalExam.WebApi.Models.Album", "Album")
                        .WithMany("Track")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("Track_AlbumId_fkey");

                    b.HasOne("FinalExam.WebApi.Models.Genre", "Genre")
                        .WithMany("Track")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("Track_GenreId_fkey");

                    b.HasOne("FinalExam.WebApi.Models.MediaType", "MediaType")
                        .WithMany("Track")
                        .HasForeignKey("MediaTypeId")
                        .HasConstraintName("Track_MediaTypeId_fkey")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
